### ISSUE TITLE
Sprint 3-5 系統實作 (Cookie)

### ISSUE THREAD

**Issue by cookieopjax** [fcu-d0813127/NftGameFormalEdition#6]

**Comment by cookieopjax** [comment]
1. 副本增加出生點
2. 怪物攻擊玩家
3. 副本增加物件使得玩家能離開地圖

**Comment by fcu-d0813127** [comment]
#### 07/07
1. 普通攻擊噴錯
![](https://i.imgur.com/sVrefxw.png)
1. 不確定是否為漏填
![](https://i.imgur.com/DlpHvoJ.png)
1. Boss卡住(觸發狀況：快速連續使用X之後產生，目前只發生一次)
![](https://i.imgur.com/rgvlksO.png)
1. Boss技能對玩家推擠
1. 怪物全打完找不到出口
1. 怪物死後嘗試把碰撞關掉

**Comment by cookieopjax** [comment]
@fcu-d0813127 

關於普攻會報錯，應該是因為Object用拉的關係
我當初改了變數名，所以要重拉，我那時有拉
但不知為何你這邊載下來後還是沒拉的狀態
所以我覺得應該之後少用拉得比較好

**Comment by fcu-d0813127** [comment]
#### 07/07
1. 普通攻擊噴錯
![](https://i.imgur.com/sVrefxw.png)
1. 不確定是否為漏填
![](https://i.imgur.com/DlpHvoJ.png)
1. Boss卡住(觸發狀況：快速連續使用X之後產生，目前只發生一次)
![](https://i.imgur.com/rgvlksO.png)
1. Boss技能對玩家推擠
1. 怪物全打完找不到出口
1. 怪物死後嘗試把碰撞關掉

**Comment by cookieopjax** [comment]
87f69df6c089a4e3b002853de8e720b258c15045
新增使玩家不能一直按K無限攻擊
而是必須間隔一段時間才能普攻
目前是設定0.4秒一次
